-- Seed: statement_bank
-- Source: statements_final.xlsx
-- 70 statements across all Focus Areas.

INSERT INTO statement_bank (focus_area, statement, type, needs_reworded, reworded_statement) VALUES
  ('Building My Comfort and Confidence in Class', 'I feel welcomed and respected by my teacher and classmates.', 'likert', FALSE, NULL),
  ('Understanding What is Taught', 'I understand the main ideas being taught in this subject.', 'likert', FALSE, NULL),
  ('Understanding What is Taught', 'The explanations in class help me understand clearly.', 'likert', FALSE, NULL),
  ('Learning at My Own Level and Speed', 'I am able to learn at a pace that works for me.', 'likert', FALSE, NULL),
  ('Feeling Ready for Tests and Exams', 'I feel ready for tests because of what we do in class.', 'likert', FALSE, NULL),
  ('Feeling Encouraged and Supported Emotionally', 'My teacher supports me when I feel stuck or unsure.', 'likert', FALSE, NULL),
  ('Building My Comfort and Confidence in Class', 'I feel comfortable and confident being myself in this class.', 'likert', TRUE, 'When in class, I don''t feel threatened or ashamed at answering openly'),
  ('Building My Comfort and Confidence in Class', 'I feel safe to speak up, even if I might be wrong.', 'likert', FALSE, NULL),
  ('Building My Comfort and Confidence in Class', 'What helps you feel most comfortable and confident in this class?', 'free_text', FALSE, NULL),
  ('Staying Focused and Respectful in Class', 'The class environment helps me stay focused and on-task.', 'likert', FALSE, NULL),
  ('Staying Focused and Respectful in Class', 'I am rarely distracted during class time.', 'likert', TRUE, 'I usually stay focused during class.'),
  ('Staying Focused and Respectful in Class', 'I know what is expected of me in terms of behaviour and discipline.', 'likert', FALSE, NULL),
  ('Staying Focused and Respectful in Class', 'What helps you stay focused and on track during class time?', 'free_text', FALSE, NULL),
  ('Asking Questions When I Don''t Understand', 'I ask questions when I don''t understand something.', 'likert', FALSE, NULL),
  ('Asking Questions When I Don''t Understand', 'I feel confident asking questions in this subject.', 'likert', FALSE, NULL),
  ('Asking Questions When I Don''t Understand', 'I believe my questions are taken seriously and answered clearly.', 'likert', FALSE, NULL),
  ('Asking Questions When I Don''t Understand', 'What makes it easy or hard for you to ask questions in this subject?', 'free_text', FALSE, NULL),
  ('Keeping Up with the Pace of Lessons', 'I can keep up with the speed of teaching in this subject.', 'likert', FALSE, NULL),
  ('Keeping Up with the Pace of Lessons', 'I have enough time to understand before moving on to new topics.', 'likert', TRUE, 'The pace of instruction allows me to fully grasp concepts before we transition to something else.'),
  ('Keeping Up with the Pace of Lessons', 'I rarely feel rushed during class.', 'likert', FALSE, NULL),
  ('Keeping Up with the Pace of Lessons', 'When do you feel the class moves too fast or too slow for you?', 'free_text', FALSE, NULL),
  ('Understanding What is Taught', 'I am able to explain what I have learned in my own words.', 'likert', TRUE, 'I can accurately summarize the lesson material using my own vocabulary.'),
  ('Understanding What is Taught', 'What kinds of explanations or examples help you understand best?', 'free_text', FALSE, NULL),
  ('Learning in Ways That Work for Me', 'The various teaching methods used in class help me learn better.', 'likert', FALSE, NULL),
  ('Learning in Ways That Work for Me', 'Activities like group work, stories, or examples help me learn better.', 'likert', TRUE, 'Collaborative tasks and real-world illustrations significantly improve my grasp of the subject.'),
  ('Learning in Ways That Work for Me', 'Visual tools like charts, videos, or slides help me understand more.', 'likert', FALSE, NULL),
  ('Learning in Ways That Work for Me', 'Which learning activities or tools help you the most in this subject?', 'free_text', FALSE, NULL),
  ('Learning in Ways That Work for Me', '(If you have used these tools in class) Do digital learning tools such as AI or Wayground help you learn more effectively?', 'likert', FALSE, NULL),
  ('Doing Homework That Helps Me Learn', 'When I receive homework it helps me understand the topic better.', 'likert', FALSE, NULL),
  ('Doing Homework That Helps Me Learn', 'When given an assignment or homework, I complete it on time', 'likert', FALSE, NULL),
  ('Doing Homework That Helps Me Learn', 'When given homework, does the homework help you understand the subject better?', 'free_text', FALSE, NULL),
  ('Learning at My Own Level and Speed', 'I get the support I need, whether I find the topic easy or difficult.', 'likert', TRUE, 'The teacher or my friends help me, regardless of how difficult the text is.'),
  ('Learning at My Own Level and Speed', 'The teacher notices when I need extra help or a bigger challenge.', 'likert', FALSE, NULL),
  ('Learning at My Own Level and Speed', 'What kind of help do you need when topics are too hard or too easy?', 'free_text', FALSE, NULL),
  ('Feeling Ready for Tests and Exams', 'I get enough revision and practice before exams.', 'likert', FALSE, NULL),
  ('Feeling Ready for Tests and Exams', 'I know what to expect in tests and feel confident answering them.', 'likert', FALSE, NULL),
  ('Feeling Ready for Tests and Exams', 'What helps you feel prepared and confident for exams in this subject?', 'free_text', FALSE, NULL),
  ('Feeling Encouraged and Supported Emotionally', 'I feel encouraged to keep trying, even when I make mistakes.', 'likert', FALSE, NULL),
  ('Feeling Encouraged and Supported Emotionally', 'I feel motivated to do my best in this subject.', 'likert', FALSE, NULL),
  ('Feeling Encouraged and Supported Emotionally', 'What motivates you most to keep trying, even when things are difficult?', 'free_text', FALSE, NULL),
  ('Staying Connected to Values in What I Learn', 'I am able to relate what I learnt in class with Kutub al-Dawah', 'likert', TRUE, 'I recognize a strong parallel between our course material and the principles taught in Kutub al-Dawah'),
  ('Staying Connected to Values in What I Learn', 'We occasionally connect what we learn in class with teachings from Awliya Allah AS.', 'likert', FALSE, NULL),
  ('Participating and Knowing How I Am Doing', 'I take part in class activities and discussions.', 'likert', FALSE, NULL),
  ('Participating and Knowing How I Am Doing', 'When assessments or competitions have been held, they have helped me.', 'likert', FALSE, NULL),
  ('Participating and Knowing How I Am Doing', 'I receive feedback that helps me improve.', 'likert', FALSE, NULL),
  ('Participating and Knowing How I Am Doing', 'I can reach out to the teacher outside of class whenever I need help.', 'likert', FALSE, NULL),
  ('Participating and Knowing How I Am Doing', 'What helps you stay engaged and understand how you''re progressing in this subject?', 'free_text', FALSE, NULL),
  ('Overall English Usage', 'To what extent is the subject always taught in English (and not in Dawat ni zabaan)', 'likert', FALSE, NULL),
  ('Overall English Usage', 'Do you feel comfortable to speak about Fatimi concepts and Dawat texts in English?', 'likert', FALSE, NULL),
  ('Usage of learning aids', 'The board and other teaching aids help me understand lessons clearly.', 'likert', FALSE, NULL),
  ('Usage of learning aids', 'There is a good balance between explanation, activities, and digital resources in class.', 'likert', FALSE, NULL),
  ('Usage of learning aids', 'Which tools help you learn the most (e.g., board, videos, Senseboard, Maʿmal)? Why?', 'free_text', FALSE, NULL),
  ('Subject-Specific questions English', 'I can understand what I read in English during class activities.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'The writing practice in class helps me become a better writer in English.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'I feel confident speaking in English during class discussions or activities.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'I can understand spoken English when my teacher or classmates speak.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'What is one thing in English class that helps you learn well, and one thing that could be improved?', 'free_text', FALSE, NULL),
  ('Subject-Specific questions English', 'What do you think about the new English books and syllabus? Please share anything you like, dislike, or think could be improved.', 'free_text', FALSE, NULL),
  ('Subject-Specific questions Lab', 'The instructions given in the lab are clear and easy to follow.', 'likert', FALSE, NULL),
  ('Subject-Specific questions Lab', 'I am able to use lab equipment and materials safely and correctly.', 'likert', FALSE, NULL),
  ('Subject-Specific questions Lab', 'I feel confident carrying out experiments and practical tasks in the lab.', 'likert', FALSE, NULL),
  ('Subject-Specific questions Lab', 'What could be done to improve your Science Laboratory experience?', 'free_text', FALSE, NULL),
  ('Subject-Specific questions Lab', 'What is one thing about the lab sessions that helps you learn well, and one thing that could be improved?', 'free_text', FALSE, NULL),
  ('Subject-Specific questions Maths', 'I feel comfortable with the coursework that is completed in class.', 'likert', FALSE, NULL),
  ('Subject-Specific questions Maths', 'I complete my Maths homework before the next class.', 'likert', FALSE, NULL),
  ('Subject-Specific questions Maths', 'There is time, with regard to Maths coursework and homework, to ask questions and go over doubts.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'I receive helpful feedback on my writing that helps me improve.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'I get enough writing practice in class to prepare for exams.', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'I am given ample opportunity to speak in class', 'likert', FALSE, NULL),
  ('Subject-Specific questions English', 'Which of the following do you think we need more of in class: reading, writing, speaking, or listening? Why?', 'free_text', FALSE, NULL);