-- server/db/migrations/025_kitabs.sql
--
-- Real gap closed: a single subject is often taught across multiple
-- classes using different kitabs (books) -- e.g. English has 5 distinct
-- kitabs across 21 classes. This dimension exists in the real source data
-- (Teachers.csv: BookClassMasterCode, BookType) but was never carried into
-- the schema. Needed for the Group/Review-Cycle feature, where a Group is
-- defined by subject and its scope (classes + kitabs) is derived
-- automatically, not manually picked.
--
-- Verified: every class+subject combination maps to exactly ONE kitab (no
-- class splits one subject across two books with different teachers), so
-- kitab_id is a simple column on class_subjects, not a junction table.

CREATE TABLE kitabs (
  id                      SERIAL PRIMARY KEY,
  subject_id              INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  book_class_master_code  TEXT NOT NULL UNIQUE,
  book_type               TEXT NOT NULL
);

ALTER TABLE class_subjects ADD COLUMN kitab_id INTEGER REFERENCES kitabs(id);

-- Real kitab data from Teachers.csv -- 61 distinct kitabs across 22 subjects.
INSERT INTO kitabs (subject_id, book_class_master_code, book_type) VALUES
  ((SELECT id FROM subjects WHERE name = 'English'), 'ENLG101-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'English'), 'ENLG102-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'English'), 'ENLG103-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'English'), 'ENLG104-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'English'), 'ENLG13-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT205-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT206-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT207-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT308-S', 'S'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT309-S', 'S'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT410-S', 'S'),
  ((SELECT id FROM subjects WHERE name = 'Literature'), 'ENLT411-S', 'S'),
  ((SELECT id FROM subjects WHERE name = 'Lab'), 'MILB101-A', 'A'),
  ((SELECT id FROM subjects WHERE name = 'Architecture'), 'SCAR309-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Biology'), 'SCBO103-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Biology'), 'SCBO104-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Biology'), 'SCBO12-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Business Studies'), 'SCBS13-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Business Studies'), 'SCBS205-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Business Studies'), 'SCBS206-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Business Studies'), 'SCBS207-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Chemistry'), 'SCCH103-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Chemistry'), 'SCCH104-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Chemistry'), 'SCCH12-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Dawat Litigation'), 'SCDL309-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Economics'), 'SCEC13-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Economics'), 'SCEC205-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Economics'), 'SCEC206-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Economics'), 'SCEC207-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Geography'), 'SCGR101-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Geography'), 'SCGR102-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Geography'), 'SCGR103-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Geography'), 'SCGR104-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'History-Civics'), 'SCHC101-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'History-Civics'), 'SCHC102-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'History'), 'SCHI13-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'History'), 'SCHI14-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'HCIW'), 'SCHW308-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Lab'), 'SCLB11-A', 'A'),
  ((SELECT id FROM subjects WHERE name = 'Lab'), 'SCLB12-A', 'A'),
  ((SELECT id FROM subjects WHERE name = 'Lab'), 'SCLB13-A', 'A'),
  ((SELECT id FROM subjects WHERE name = 'Lab'), 'SCLB14-A', 'A'),
  ((SELECT id FROM subjects WHERE name = 'Linguistics'), 'SCLN411-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Management'), 'SCMG308-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Maths'), 'SCMT101-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Maths'), 'SCMT102-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Maths'), 'SCMT103-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Maths'), 'SCMT104-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Maths'), 'SCMT13-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Physics'), 'SCPH102-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Physics'), 'SCPH103-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Physics'), 'SCPH104-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Political Science'), 'SCPS411-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Psychology'), 'SCPY410-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Religions of the World'), 'SCRW410-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Science'), 'SCSC11-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Science'), 'SCSC12-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Sociology'), 'SCSO13-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Sociology'), 'SCSO205-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Sociology'), 'SCSO206-N', 'N'),
  ((SELECT id FROM subjects WHERE name = 'Sociology'), 'SCSO207-N', 'N');

-- Backfill class_subjects.kitab_id for all 187 real (class, subject, teacher) rows.
-- Matches the SAME join keys already used by class_subjects itself.
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC11-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC11-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '30410170';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC11-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC11-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '20441281';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC11-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '30427046';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC12-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '30318687';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC12-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '30493099';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC12-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '30415472';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSC12-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Science') AND teacher_its = '30410170';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '50459490';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '60434690';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '20359132';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI14-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI14-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '60434690';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI14-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI14-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '30408579';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHI14-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB11-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'MILB101-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB11-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'MILB101-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB11-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB12-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB12-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB12-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB12-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB12-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB13-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB13-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB13-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB13-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB13-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB14-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB14-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB14-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB14-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLB14-A') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Lab') AND teacher_its = '';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '50445721';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '20359132';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '20359594';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '60434690';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '20359564';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCSO207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Sociology') AND teacher_its = '30338702';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCRW410-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '10 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Religions of the World') AND teacher_its = '20359594';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPY410-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '10 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Psychology') AND teacher_its = '30338702';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPS411-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '11 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Political Science') AND teacher_its = '20359029';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '30408307';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '30318687';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '30313408';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '30318687';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '40465833';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '30408307';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCPH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Physics') AND teacher_its = '30408307';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30312593';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '20361076';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '50445721';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30312593';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30312593';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '20361076';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30312593';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40465833';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30461609';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30304124';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30312593';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '30461609';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '20329898';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMT104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Maths') AND teacher_its = '40455878';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCMG308-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '8 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Management') AND teacher_its = '5231 Dr.';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCLN411-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '11 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Linguistics') AND teacher_its = '30338702';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHW308-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '8 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'HCIW') AND teacher_its = '50459490';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30409042';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30476900';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30313106';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30408579';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30415472';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCHC102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'History-Civics') AND teacher_its = '30476900';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30355689';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30441198';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30410170';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '20359704';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '20359440';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30461609';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30427046';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30408223';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30408223';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30408223';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30494003';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30408223';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '20359132';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30410170';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCGR104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Geography') AND teacher_its = '30304124';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '30306764';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '30306764';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '20359050';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '30306764';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '30316376';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '30306764';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '50492566';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '50492566';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '30306764';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCEC207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Economics') AND teacher_its = '50492566';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCDL309-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '9 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Dawat Litigation') AND teacher_its = '78652315';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH12-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '30496801';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '30313408';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '30408307';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '50445721';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '30318687';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '30408307';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCCH104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Chemistry') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBS13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Business Studies') AND teacher_its = '5200 Dr.';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBS205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Business Studies') AND teacher_its = '30418524';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBS205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Business Studies') AND teacher_its = '5200 Dr.';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBS206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Business Studies') AND teacher_its = '5200 Dr.';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBS206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Business Studies') AND teacher_its = '5200 Dr.';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBS207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Business Studies') AND teacher_its = '30418524';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO12-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '30493099';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '30313408';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '40431121';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '20441281';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '30461609';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCBO104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Biology') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'SCAR309-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '9 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Architecture') AND teacher_its = '20359506';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT308-S') WHERE class_id = (SELECT id FROM classes WHERE display_name = '8 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '40418736';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT309-S') WHERE class_id = (SELECT id FROM classes WHERE display_name = '9 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '50459490';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT410-S') WHERE class_id = (SELECT id FROM classes WHERE display_name = '10 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '20359506';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT411-S') WHERE class_id = (SELECT id FROM classes WHERE display_name = '11 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '30338702';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '50409731';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '30338702';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '78652397';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT205-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '5 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '78652222';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '30304124';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '20359594';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT206-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '6 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '20441281';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '30375979';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLT207-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '7 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'Literature') AND teacher_its = '50459490';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30313106';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '40418736';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30494003';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '40489336';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG101-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '1 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '50409739';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30313106';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30408579';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30375979';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '40465833';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG102-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '2 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30375979';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '78652397';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '20361076';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30494003';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '20378168';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG103-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30338702';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG13-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '3 DARS F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '20359050';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30375979';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 A M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '20359564';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30494003';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 B M') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30316376';
UPDATE class_subjects SET kitab_id = (SELECT id FROM kitabs WHERE book_class_master_code = 'ENLG104-N') WHERE class_id = (SELECT id FROM classes WHERE display_name = '4 C F') AND subject_id = (SELECT id FROM subjects WHERE name = 'English') AND teacher_its = '30375979';